#!/bin/sh
xrandr --output DP-4 --primary --mode 2560x1600 --rate 165.02 --output DP-2 --above DP-4 --output DP-0 --mode 1920x1080 --rate 239.96 --left-of DP-2 --output HDMI-0 --right-of DP-2
feh --bg-scale ~/Arduino/docs/schematics.png
