#!/bin/sh

# Simple dmenu prompt to set audio level

level="$(printf "   " | dmenu -p "Audio level:")"

case "${level#[+-]}" in
	(*[!0123456789]*) return 1 ;;
	('')              return 1 ;;
	(*)               ;;
esac

if [ $level -le 100 ] && [ $level -ge 0 ];
then
	amixer -c 1 set Master "$level%" &> /dev/null
else
	return 1
fi
