#!/bin/sh

# Simple dmenu prompt to set audio level

currentlevel="$(pamixer --get-volume-human)"
level="$(printf "   " | dmenu -p "$currentlevel - Audio level:")"

if [ "$level" -le 100 ] && [ "$level" -ge 0 ];
then
	pamixer --set-volume "$level"
else
	dunstify "Invalid volume level"
	return 1
fi

return 0
