#!/bin/sh

action="$(printf 'Shut Down\nReboot\nLock Screen\nQuit BSPWM\nReload BSPWM' | dmenu -l 5 -i)"

[ "$action" = "Shut Down" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && shutdown 0

[ "$action" = "Reboot" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && reboot

[ "$action" = "Lock Screen" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && slock

[ "$action" = "Quit BSPWM" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && killall polybar && bspc quit

[ "$action" = "Reload BSPWM" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && bspc wm -r

exit
