#!/bin/sh

action="$(printf 'Shut Down\nLock Screen\nQuit BSPWM' | dmenu -l 3 -i)"

[ "$action" = "Shut Down" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && shutdown 0

[ "$action" = "Lock Screen" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && slock

[ "$action" = "Quit BSPWM" ] && answer="$(printf 'Yes\nNo' | dmenu -l 2 -i -p "Confirm:")"
[ "$answer" = "Yes" ] && bspc quit
