#!/bin/sh

# Author: sandalbanditten
# License: GPL v3.0

# smart way
folder="$(ls $HOME/Pictures/ | dmenu -l 16 -i -p 'Image folder:')"
[ $folder ] && imv -b '#282828' -- $HOME/Pictures/$folder/
exit
