#!/bin/sh

# Author: sandalbanditten
# License: GPL v3.0

# smart way
folder="$(ls $HOME/Pictures/ | dmenu -l 16 -i -p 'Image folder:')"
[ $folder ] && image="$(ls $HOME/Pictures/$folder/* -1 | dmenu -l 16 -i -p 'Image:')"
[ $image ] && imv -b '#2e3440' -- $image
